### ISSUE TITLE
Give option to change plotting theme

### ISSUE THREAD

**Issue by erictleung** [erictleung/shinydiversity#23]
The plots created in `phyloseq` are ggplot2 based. 

Some places to look at for themes.

- Built-in ggplot2 themes http://ggplot2.tidyverse.org/reference/index.html#section-themes
- ggthemes package https://cran.r-project.org/web/packages/ggthemes/vignettes/ggthemes.html
- Build custom theme examples http://sape.inf.usi.ch/quick-reference/ggplot2/themes

**Comment by ampatzia** [comment]
Theme change was erased in commit [alphaDiversityUpdated](https://github.com/erictleung/shinydiversity/commit/4ff60be934e2b975f57245ce8692b19b7c58eda6) can be re-implemented easily if still desired as a feature.
