### ISSUE TITLE
Problem in documentation section from  function knit

### ISSUE THREAD

**Issue by ampatzia** [erictleung/shinydiversity#38]
docs\ui.R throws `Error : could not find function "knit" in local run   `
this can be corrected changing
`  knit("docs/alpha.Rmd", "docs/alpha.md", quiet = TRUE)`
to
` knitr::knit("docs/alpha.Rmd", "docs/alpha.md", quiet = TRUE)`
in line 6.

**Comment by erictleung** [comment]
@ampatzia you'll need the package `knitr` to use the function `knit`. I think this might be a general problem of having the right packages installed before using this application. 

To make this better, we could probably create a `global.R` file and have an install script similar to one in [`shiny-phyloseq`](https://github.com/joey711/shiny-phyloseq/blob/master/install.R).

**Comment by ampatzia** [comment]
Had it already but problem seems fixed in last version, closing issue down.
