### ISSUE TITLE
Lack of SampleType in alpha diversity breaks plot

### ISSUE THREAD

**Issue by ampatzia** [erictleung/shinydiversity#54]
Addition of sample type legend in Alpha Diversity measure causes the `Error: object 'SampleType' not found` where obviously this trait is missing. Error is reproducible at the time of posting by choosing Esophagus dataset. [Screenshot of error](https://image.prntscr.com/image/CzDwPBK_Rj6QP8XNCI57Sg.png).

**Comment by erictleung** [comment]
This make sense, unfortunately. The issue is this line (https://github.com/erictleung/shinydiversity/blob/master/alpha/server.R#L10). It asks for the `SampleType` to be colored, but there is no `SampleType` for the `esophagus` dataset.

**Comment by aimirza** [comment]
Codes should be modified separately for each dataset. `color = "SampleType"` should be removed for the  esophagus dataset.
