### ISSUE TITLE
Maybe consider using Shiny-phyloseq instead...

### ISSUE THREAD

**Issue by joey711** [erictleung/shinydiversity#55]
Or at least acknowledging it somewhere in your code/doc/etc.

http://joey711.github.io/shiny-phyloseq/

**Comment by erictleung** [comment]
@joey711 thanks for the suggestion! Yeah, there has been a couple applications which aim to make interacting with phyloseq objects and analyzing microbiome data easier. I'll be sure to add a shoutout to shiny-phyloseq :+1:
